<?php
/* ***********************************************************************************************
 *
 * Phoebius Framework v.1.0.0
 *
 * **********************************************************************************************
 *
 * This is an auxiliary autogenerated file. Do not edit it as it can be regenerated implicitly!
 *
 ************************************************************************************************/

/**
 * Autogenerated class
 */
abstract class AutoContentPage extends IdentifiableOrmEntity implements IOrmRelated, IDaoRelated
{
	/**
	 * @var scalar|null
	 */
	protected $id;

	/**
	 * @var scalar
	 */
	protected $title;

	/**
	 * @var scalar
	 */
	protected $text;

	/**
	 * @return ContentPageEntity
	 */
	static function orm()
	{
		return ContentPageEntity::getInstance();
	}

	/**
	 * @return IOrmEntityMapper
	 */
	static function map()
	{
		return self::orm()->getMap();
	}

	/**
	 * @return IOrmEntityAccessor
	 */
	static function dao()
	{
		return self::orm()->getDao();
	}

	/**
	 * @return EntityQuery
	 */
	static function query()
	{
		return new EntityQuery(self::orm());
	}

	/**
	 * @param scalar $id
	 * @return ContentPage itself
	 */
	function setId($id = null)
	{
		$this->id = $id;

		return $this;
	}

	function _setId($id)
	{
		$this->setId($id);

		return $this;
	}

	/**
	 * @return mixed|null
	 */
	function getId()
	{
		return $this->id;
	}

	function _getId()
	{
		return $this->getId();
	}

	/**
	 * @param scalar $title
	 * @return ContentPage itself
	 */
	function setTitle($title)
	{
		$this->title = $title;

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getTitle()
	{
		return $this->title;
	}

	/**
	 * @param scalar $text
	 * @return ContentPage itself
	 */
	function setText($text)
	{
		$this->text = $text;

		return $this;
	}

	/**
	 * @return mixed
	 */
	function getText()
	{
		return $this->text;
	}
}

?>